<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable Condition="'$(Configuration)'=='Release'">true</IsPackable>
		<TargetFrameworks>net$(DotNet_Version);netstandard2.0</TargetFrameworks>
		<Description>MiSans Global 是由小米主导，联合蒙纳字库、汉仪字库共同打造的全球语言字体定制项目。这是一个庞大的字体家族，涵盖 20 多种书写系统，支持 600 多种语言，字符数量超过 10 万个。作为 Xiaomi HyperOS 系统默认字体，我们以简约/清晰，人文/易读，统一的视觉风格为基本原则出发，构建多语言信息体验一致性，旨在帮助为 Xiaomi HyperOS 提供互联的通用体验</Description>
		<RootNamespace>BD.Avalonia8.Fonts</RootNamespace>
		<!--8.yy.1MMdd.1hhmm-->
		<Version>8.25.10618.11900</Version>
		<FileVersion>$(Version)</FileVersion>
		<AssemblyVersion>$(Version)</AssemblyVersion>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="**\*.ttf" />
	</ItemGroup>

	<!-- 👇 引用 NuGet 包 -->
	<ItemGroup>
		<PackageReference Include="Avalonia" PrivateAssets="all" />
	</ItemGroup>

</Project>
