<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable Condition="'$(Configuration)'=='Release'">true</IsPackable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Description>提供动图控件，支持 Gif/Apng</Description>
		<!--8.yy.1MMdd.1hhmm-->
		<Version>8.25.10606.11900</Version>
		<FileVersion>$(Version)</FileVersion>
		<AssemblyVersion>$(Version)</AssemblyVersion>
	</PropertyGroup>

	<Import Project="$(MSBuildThisFileDirectory)..\TFM_NETX_ALL.props" />

	<!-- 📄 源码引用 LibAPNG -->
	<ItemGroup>
		<Compile Include="$(MSBuildThisFileDirectory)..\LibAPNG\**\*.cs">
			<LinkBase>_SourceReference\LibAPNG</LinkBase>
			<Exclude>bin\**;obj\**</Exclude>
		</Compile>
		<Compile Remove="$(MSBuildThisFileDirectory)..\LibAPNG\bin\**\*.cs" />
		<Compile Remove="$(MSBuildThisFileDirectory)..\LibAPNG\obj\**\*.cs" />
	</ItemGroup>

	<!-- 👇 引用 NuGet 包 -->
	<ItemGroup>
		<PackageReference Include="Avalonia" PrivateAssets="all" />
		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Bcl\BD.Common8.Bcl.csproj" />
		<ProjectReference Include="$(Path_Submodule_Common)src\BD.Common8.Http.ClientFactory\BD.Common8.Http.ClientFactory.csproj" />
	</ItemGroup>

</Project>
